inc:
  # Blog Information
  title:        "Luca Guidi"
  subtitle:     "Software Engineer"
  cover_image:  cover.jpg
  logo:         logo.png

  # Company information
  company:      Luca Guidi
  url:          http://lucaguidi.com/
  facebook:     luca.guidi
  twitter:      jodosha
  about_link:   /about.html

  # Sharing settings
  sharing:
    twitter:    true
    facebook:   true
    gplus:      true
    hn:         true

 # Analytics
  analytics:
    google:
      id: 'UA-235843-4'

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Lato:400,900'

gems:        [jekyll-paginate]
url:         https://lucaguidi.com
domain:      lucaguidi.com
source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     ['Rakefile', 'Gemfile', 'Gemfile.lock']
timezone:    nil

# Show future posts
future:      false
show_drafts: nil
limit_posts: 0
highlighter: pygments

permalink:     date
paginate_path: 'page/:num'
paginate: 5

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "<!-- more -->"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

coderay:
  coderay_wrap: div
  coderay_line_numbers: inline
  coderay_line_numbers_start: 1
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: style

redcloth:
  hard_breaks: true

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false
