baseurl = "https://lucaguidi.com/"
copyright = "All rights reserved - 2018"
disqusshortname = "lucaguidi"
languagecode = "en-US"
paginate = 5
pluralizelisttitles = false
theme = "casper"
title = "Luca Guidi"
pygmentsuseclasses  = true
pygmentscodefences  = true

[[menu.main]]
name = "Twitter"
url = "https://twitter.com/jodosha"
pre = "<h3>Follow me</h3>"
weight = 200
[[menu.main]]
name = "Github"
url = "https://github.com/jodosha"
weight = 190
[[menu.main]]
name = "Keybase"
url = "https://keybase.io/jodosha"
weight = 180
[[menu.main]]
name = "Facebook"
url = "https://www.facebook.com/Luca-Guidi-1603307663019001"
weight = 170
[[menu.main]]
name = "Instagram"
url = "https://www.instagram.com/jodosha/"
weight = 160
[[menu.main]]
name = "Snapchat"
url = "https://www.snapchat.com/add/jodosha23"
weight = 150
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120

[params]
  author = "Luca Guidi"
  authorlocation = "Rome, Italy"
  authorwebsite = "https://lucaguidi.com"
  description = "Family man, software engineer, Open Source indie developer, speaker."
  authorbio = "Family man, software engineer, Open Source indie developer, speaker."
  cover = "images/cover.jpg"
  githubName = "jodosha"
  googleAnalyticsUserID = "UA-235843-4"
  hideHUGOSupport = false
  logo = "assets/img/logo-default.png"
  twitterName = "jodosha"
  hjsStyle="ocean"

[permalinks]
  fixed = ":title/"
  post = "/:year/:month/:day/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"
