# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "jodosha"
license = "MIT"
licenselink = "https://github.com/jodosha/jodosha.github.io/blob/master/LICENSE.md"
description = ""
homepage = "https://lucaguidi.com"
tags = ["", ""]
features = ["", ""]
min_version = 0.18

[author]
  name = "Luca Guidi"
  homepage = "https://lucaguidi.com"
